/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BrandSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'id', 'ipWhitelist', 'logo', 'name', 'securityCode', 'status', 'updatedAt', 'url'] as const
  $columns = BrandSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ipWhitelist: any | null
  @column()
  declare logo: string | null
  @column()
  declare name: string
  @column()
  declare securityCode: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare url: string | null
}

export class CommissionPlanAssignmentSchema extends BaseModel {
  static $columns = ['affiliateId', 'brandId', 'commissionPlanId', 'createdAt', 'endsAt', 'id', 'programId', 'startsAt', 'status', 'updatedAt'] as const
  $columns = CommissionPlanAssignmentSchema.$columns
  @column()
  declare affiliateId: string | null
  @column()
  declare brandId: string | null
  @column()
  declare commissionPlanId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare endsAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare programId: string
  @column.dateTime()
  declare startsAt: DateTime | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CommissionPlanTierSchema extends BaseModel {
  static $columns = ['commissionPlanId', 'cpaAmount', 'createdAt', 'id', 'maxValue', 'minValue', 'revsharePercentage', 'updatedAt'] as const
  $columns = CommissionPlanTierSchema.$columns
  @column()
  declare commissionPlanId: string
  @column()
  declare cpaAmount: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare maxValue: string
  @column()
  declare minValue: string
  @column()
  declare revsharePercentage: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CommissionPlanSchema extends BaseModel {
  static $columns = ['cpaAmount', 'cpaTriggerDeposit', 'cpaTriggerWager', 'createdAt', 'deletedAt', 'hasNegativeCarryover', 'id', 'isTiered', 'model', 'name', 'revsharePercentage', 'updatedAt'] as const
  $columns = CommissionPlanSchema.$columns
  @column()
  declare cpaAmount: string | null
  @column()
  declare cpaTriggerDeposit: string | null
  @column()
  declare cpaTriggerWager: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare hasNegativeCarryover: boolean | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isTiered: boolean | null
  @column()
  declare model: string
  @column()
  declare name: string
  @column()
  declare revsharePercentage: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PasswordResetTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'expiresAt', 'id', 'token', 'updatedAt'] as const
  $columns = PasswordResetTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare email: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare token: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PermissionRoleSchema extends BaseModel {
  static $columns = ['permissionId', 'roleId'] as const
  $columns = PermissionRoleSchema.$columns
  @column({ isPrimary: true })
  declare permissionId: string
  @column()
  declare roleId: string
}

export class PermissionSchema extends BaseModel {
  static $columns = ['createdAt', 'group', 'id', 'name', 'slug', 'updatedAt'] as const
  $columns = PermissionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare group: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string | null
  @column()
  declare slug: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProgramBrandSchema extends BaseModel {
  static $columns = ['brandId', 'id', 'programId'] as const
  $columns = ProgramBrandSchema.$columns
  @column()
  declare brandId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare programId: string
}

export class ProgramSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'id', 'name', 'status', 'updatedAt'] as const
  $columns = ProgramSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RoleUserSchema extends BaseModel {
  static $columns = ['roleId', 'userId'] as const
  $columns = RoleUserSchema.$columns
  @column()
  declare roleId: string
  @column({ isPrimary: true })
  declare userId: string
}

export class RoleSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'slug', 'updatedAt'] as const
  $columns = RoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SettingSchema extends BaseModel {
  static $columns = ['createdAt', 'group', 'id', 'key', 'name', 'updatedAt', 'value'] as const
  $columns = SettingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare group: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare key: string
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare value: any | null
}

export class UserSchema extends BaseModel {
  static $columns = ['companyName', 'createdAt', 'deletedAt', 'email', 'emailVerificationToken', 'emailVerifiedAt', 'fullName', 'id', 'meta', 'password', 'status', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare companyName: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: string
  @column()
  declare emailVerificationToken: string | null
  @column.dateTime()
  declare emailVerifiedAt: DateTime | null
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare meta: any | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
